version: '3'

services:

  front:
    image: front
    container_name: front
    env_file: .env
    volumes:
      - transcendence:/home
    build: 
      context: requirements/front
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3001:3000"
      - "3001:3001"
    #expose: 
    # - "3000"
    stdin_open: true
    tty: true

  back:
    image: back
    container_name: back
    env_file: .env
    volumes:
      - transcendence:/home
    build: 
      context: requirements/back
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5432:5432"
      - "3000:3000"
    expose: 
      - "5432"
      - "3000"
    stdin_open: true
    tty: true

volumes:
  transcendence:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
        #device: '/mnt/nfs/homes/hboissel/data'
      device: '/home/hboissel/data'
